// Command branchswitch finds Go functions with repeated simple if branches
// and writes a sorted markdown checklist for manual review.
package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

type funcReport struct {
	File     string
	Func     string
	Line     int
	Branches int
	Inits    int
	Notes    []string
}

func main() {
	root := flag.String("path", ".", "directory to scan")
	out := flag.String("out", "", "markdown output path (default: .cursor/skills/go-switch/branches.md under root)")
	min := flag.Int("min", 3, "minimum if branches to list a function")
	flag.Parse()

	if *out == "" {
		*out = filepath.Join(*root, ".cursor", "skills", "go-switch", "branches.md")
	}

	fset := token.NewFileSet()
	byFunc := make(map[string]*funcReport)

	err := filepath.WalkDir(*root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			base := filepath.Base(path)
			switch base {
			case "vendor", ".git", "testdata", ".cursor":
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		if strings.HasSuffix(path, "_gen.go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}

		file, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			return nil
		}

		rel, _ := filepath.Rel(*root, path)
		if rel == "" {
			rel = filepath.Base(path)
		}
		rel = filepath.ToSlash(rel)

		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Body == nil {
				continue
			}
			name := funcName(fn)
			key := rel + "\x00" + name
			report := &funcReport{
				File: rel,
				Func: name,
				Line: fset.Position(fn.Pos()).Line,
			}
			countBranches(fset, fn.Body, report)
			if report.Branches >= *min {
				byFunc[key] = report
			}
		}
		return nil
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "branchswitch: %v\n", err)
		os.Exit(1)
	}

	reports := make([]*funcReport, 0, len(byFunc))
	for _, r := range byFunc {
		reports = append(reports, r)
	}
	sort.Slice(reports, func(i, j int) bool {
		if reports[i].Branches != reports[j].Branches {
			return reports[i].Branches > reports[j].Branches
		}
		if reports[i].File != reports[j].File {
			return reports[i].File < reports[j].File
		}
		return reports[i].Func < reports[j].Func
	})

	if err := writeMarkdown(*out, *root, *min, reports); err != nil {
		fmt.Fprintf(os.Stderr, "branchswitch: %v\n", err)
		os.Exit(1)
	}
	fmt.Println(*out)
}

func funcName(fn *ast.FuncDecl) string {
	name := fn.Name.Name
	if fn.Recv == nil || len(fn.Recv.List) == 0 {
		return name
	}
	switch t := fn.Recv.List[0].Type.(type) {
	case *ast.StarExpr:
		if id, ok := t.X.(*ast.Ident); ok {
			return id.Name + "." + name
		}
	case *ast.Ident:
		return t.Name + "." + name
	}
	return name
}

func countBranches(fset *token.FileSet, body *ast.BlockStmt, report *funcReport) {
	ast.Inspect(body, func(n ast.Node) bool {
		switch node := n.(type) {
		case *ast.SwitchStmt:
			return false
		case *ast.TypeSwitchStmt:
			return false
		case *ast.IfStmt:
			if node.Else != nil {
				return true
			}
			exit, sideEffect := bodyKind(node.Body)
			if exit == bodyOther {
				return true
			}
			report.Branches++
			if node.Init != nil {
				report.Inits++
				report.Notes = append(report.Notes, "if-init: "+stmtString(fset, node.Init)+"; "+exprString(fset, node.Cond))
			} else {
				report.Notes = append(report.Notes, exprString(fset, node.Cond))
			}
			if sideEffect {
				report.Notes = append(report.Notes, "(side-effect-only body at line "+fmt.Sprint(fset.Position(node.Pos()).Line)+")")
			}
		}
		return true
	})
}

func writeMarkdown(path, root string, min int, reports []*funcReport) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("# Go switch candidates\n\n")
	b.WriteString("Generated by `branchswitch`. Work top to bottom; mark done with `[x]`.\n")
	b.WriteString("Branch count includes guard-style `if` statements only; `switch` is not counted.\n\n")
	fmt.Fprintf(&b, "Scanned: `%s`  \n", filepath.ToSlash(root))
	fmt.Fprintf(&b, "Minimum branches: %d  \n", min)
	fmt.Fprintf(&b, "Generated: %s  \n\n", time.Now().Format(time.RFC3339))

	if len(reports) == 0 {
		b.WriteString("_No functions with enough branch ifs found._\n")
		return os.WriteFile(path, []byte(b.String()), 0o644)
	}

	for _, r := range reports {
		fmt.Fprintf(&b, "[ ] %d branches, function %s(), file %s\n", r.Branches, r.Func, r.File)
	}
	b.WriteString("\n## Details\n\n")
	for _, r := range reports {
		fmt.Fprintf(&b, "### `%s()` — %s (%d branches)\n\n", r.Func, r.File, r.Branches)
		if r.Inits > 0 {
			fmt.Fprintf(&b, "- %d branch(es) with init statement (cannot move into `case` directly)\n", r.Inits)
		}
		for _, note := range r.Notes {
			if strings.HasPrefix(note, "(side-effect-only") {
				fmt.Fprintf(&b, "- %s\n", note)
				continue
			}
			fmt.Fprintf(&b, "- `%s`\n", note)
		}
		b.WriteString("\n")
	}

	return os.WriteFile(path, []byte(b.String()), 0o644)
}

type bodyExitKind int

const (
	bodyOther bodyExitKind = iota
	bodyReturn
	bodySideEffect
)

func bodyKind(block *ast.BlockStmt) (bodyExitKind, bool) {
	if block == nil || len(block.List) == 0 {
		return bodyOther, false
	}
	if len(block.List) > 3 {
		return bodyOther, false
	}
	hasReturn := false
	hasSideEffect := false
	for _, stmt := range block.List {
		switch s := stmt.(type) {
		case *ast.ReturnStmt:
			hasReturn = true
		case *ast.DeferStmt:
			continue
		case *ast.BranchStmt:
			if s.Tok == token.CONTINUE || s.Tok == token.BREAK {
				hasReturn = true
				continue
			}
			return bodyOther, false
		case *ast.ExprStmt:
			if call, ok := s.X.(*ast.CallExpr); ok && isExitCall(call) {
				hasReturn = true
				continue
			}
			hasSideEffect = true
		default:
			return bodyOther, false
		}
	}
	if hasReturn {
		return bodyReturn, false
	}
	if hasSideEffect {
		return bodySideEffect, true
	}
	return bodyOther, false
}

func isExitCall(call *ast.CallExpr) bool {
	switch fun := call.Fun.(type) {
	case *ast.Ident:
		switch fun.Name {
		case "panic", "Fatal", "Fatalf", "Fatalln", "FailNow":
			return true
		}
	case *ast.SelectorExpr:
		if id, ok := fun.X.(*ast.Ident); ok {
			switch id.Name + "." + fun.Sel.Name {
			case "log.Fatal", "log.Fatalf", "log.Fatalln":
				return true
			}
		}
	}
	return false
}

func exprString(fset *token.FileSet, expr ast.Expr) string {
	var b strings.Builder
	_ = printer.Fprint(&b, fset, expr)
	return b.String()
}

func stmtString(fset *token.FileSet, stmt ast.Stmt) string {
	var b strings.Builder
	_ = printer.Fprint(&b, fset, stmt)
	return b.String()
}
